@baseUrl = http://localhost:8080/consultas
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJleHAiOjE2NzczMzYyMTN9.Ok4MVg2YvSuEp-IVtF3sWCqawPNRpDKdqy704RTcHSU

###
post {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "idPaciente": 2,
    "especialidade": "CARDIOLOGIA",
    "data": "2023-10-10T11:00:00"
}
