@baseUrl = http://localhost:8080/medicos

###
post {{baseUrl}}
Content-Type: application/json

# {
#     "nome": "Rodrigo Ferreira",
#     "email": "rodrigo.ferreira@voll.med",
#     "crm": "123456",
#     "especialidade": "ORTOPEDIA",
#     "endereco": {
#         "logradouro": "rua 1",
#         "bairro": "bairro",
#         "cep": "12345678",
#         "cidade": "Brasilia",
#         "uf": "DF",
#         "numero": "1",
#         "complemento": "complemento"
#         }
# }

# {
#     "nome": "Joao Carlos",
#     "email": "joao.carlos@voll.med",
#     "crm": "54333",
#     "especialidade": "ORTOPEDIA",
#     "endereco": {
#         "logradouro": "rua x",
#         "bairro": "bairro",
#         "cep": "98765443",
#         "cidade": "Brasilia",
#         "uf": "DF",
#         "numero": "14",
#         "complemento": "complemento"
#         }
# }

{
    "nome": "Bruna Silvz",
    "email": "bruna.silva@voll.med",
    "telefone": "83999022334",
    "crm": "231243",
    "especialidade": "CARDIOLOGIA",
    "endereco": {
        "logradouro": "rua tr",
        "bairro": "bairro",
        "cep": "58033044",
        "cidade": "JOÃO PESSOA",
        "uf": "PB",
        "numero": "44",
        "complemento": "complemento"
        }
}

###
get {{baseUrl}}

###
get {{baseUrl}}?size=1&page=2

###
get {{baseUrl}}?sort=crm,desc

###
get {{baseUrl}}/5

###
put {{baseUrl}}
Content-Type: application/json

{
    "id": 2,
    "telefone": "2112345678"
}

###
delete {{baseUrl}}/1