@baseUrl = http://localhost:8080/pacientes
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJleHAiOjE2NzczMzYyMTN9.Ok4MVg2YvSuEp-IVtF3sWCqawPNRpDKdqy704RTcHSU

###
post {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Brock Hangman",
    "email": "brock.hangmant@voll.med",
    "cpf": "33333333333",
    "telefone": "88 98745332",
    "endereco": {
        "logradouro": "rua z",
        "bairro": "bairro",
        "cep": "55443334",
        "cidade": "Cajá",
        "uf": "PB",
        "numero": "112",
        "complemento": "complemento"
        }
}

###
get {{baseUrl}}
Authorization: Bearer {{token}}

###
get {{baseUrl}}?size=1&page=0
Authorization: Bearer {{token}}

###
get {{baseUrl}}?sort=nome,desc
Authorization: Bearer {{token}}

###
get {{baseUrl}}/1
Authorization: Bearer {{token}}

###
delete {{baseUrl}}/3
Authorization: Bearer {{token}}